### ISSUE TITLE
Feature request - honor indentation settings to use spaces or tabs

### ISSUE THREAD

**Issue by jamie-burks** [mgesbert/vscode-indent-nested-dictionary#4]
Currently using tabs for indentation is hard-coded. Would be nice to have the code honor the current editor indentation setting for indentation and use tabs or the configured number of spaces.

Awesome and incredibly useful extension!!

**Comment by mgesbert** [comment]
Hi @jamie-burks, thanks for the suggestion. I'm currently unable to publish updates, I'll take care of it in a few weeks.

I'm happy you found my little extension useful 🙂

**Comment by AMMullan** [comment]
Presume this extension is not being maintained? No progress on this vital setting, quite a shame :(

**Comment by mgesbert** [comment]
Hi, I'm really sorry I let this extension down for so long. I just published an update to take the user-defined indent setting into account. I hope it solves your issue if you're still using it 🙂
