### ISSUE TITLE
No newline for empty dicts and lists

### ISSUE THREAD

**Issue by JensMadsen** [mgesbert/vscode-indent-nested-dictionary#6]
Hi 

Thank you for your tool. Really helpful. I use it to format several test fixtures. Your tool makes it easier to get an overview of complex data structures. However, I think that the readability would improve if no newlines were added for empty lists and objects(dicts). Example with this `{"foo":[{}]}`: 

Now:
```json 
{
	"foo": [
		{
		}
	]
}
```

Future:

```json 
{
	"foo": [{}]
}
```

**Comment by mgesbert** [comment]
Hello, sorry for the (very) late answer, I just published a version which will format `{"foo":[{}]}` like this:
```json
{
	"foo": [
		{}
	]
}
```
Going further than that would imply adding a lot of complexity, and I want to keep this extension's logic very simple. I hope you like this change if you're still using it 🙂
